domain_path: C:\Users\Ignatev\Desktop\ResearchProject\Vitis_Projects\SK9822_ZTurn\platform_tests\export\platform_tests\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
