# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrants.xdc

# Block Designs: bd/design_main/design_main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main || ORIG_REF_NAME==design_main} -quiet] -quiet

# IP: bd/design_main/ip/design_main_processing_system7_0_2/design_main_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_processing_system7_0_2 || ORIG_REF_NAME==design_main_processing_system7_0_2} -quiet] -quiet

# IP: bd/design_main/ip/design_main_SK9822_AXI4_30_0_0/design_main_SK9822_AXI4_30_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_SK9822_AXI4_30_0_0 || ORIG_REF_NAME==design_main_SK9822_AXI4_30_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xbar_1/design_main_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_xbar_1 || ORIG_REF_NAME==design_main_xbar_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_ps7_0_axi_periph_3/design_main_ps7_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_ps7_0_axi_periph_3 || ORIG_REF_NAME==design_main_ps7_0_axi_periph_3} -quiet] -quiet

# IP: bd/design_main/ip/design_main_rst_ps7_0_25M_0/design_main_rst_ps7_0_25M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_rst_ps7_0_25M_0 || ORIG_REF_NAME==design_main_rst_ps7_0_25M_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xlconcat_0_0/design_main_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_xlconcat_0_0 || ORIG_REF_NAME==design_main_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_auto_pc_0/design_main_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_auto_pc_0 || ORIG_REF_NAME==design_main_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Daniil/Desktop/ResearchProject/Vivado_Projects/SK9822_ZTurn_30LEDs/SK9822_ZTurn.gen/sources_1/bd/design_main/design_main_ooc.xdc
