// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SK9822_transmit_fullcolors (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_SPI_D,
        out_SPI_D_ap_vld,
        out_SPI_DS,
        out_SPI_DS_ap_vld,
        in_GBCR_INSEL_val,
        in_GBCR_GB_val,
        in_LEDs_val
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] out_SPI_D;
output   out_SPI_D_ap_vld;
output  [0:0] out_SPI_DS;
output   out_SPI_DS_ap_vld;
input  [0:0] in_GBCR_INSEL_val;
input  [4:0] in_GBCR_GB_val;
input  [95:0] in_LEDs_val;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] conv9_fu_107_p1;
reg   [7:0] conv9_reg_244;
wire   [1:0] led_byte_id_fu_131_p1;
reg   [1:0] led_byte_id_reg_252;
wire    ap_CS_fsm_state2;
wire   [31:0] LED_i_fu_162_p1;
reg   [31:0] LED_i_reg_258;
wire   [7:0] led_byte_i_fu_187_p1;
reg   [7:0] led_byte_i_reg_263;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln18_fu_191_p2;
reg   [0:0] icmp_ln18_reg_268;
wire   [7:0] led_byte_i_1_fu_196_p3;
reg   [7:0] led_byte_i_1_reg_273;
wire   [7:0] led_byte_i_3_fu_220_p3;
reg   [7:0] led_byte_i_3_reg_279;
wire    ap_CS_fsm_state4;
wire    grp_transmit_byte_fu_86_ap_start;
wire    grp_transmit_byte_fu_86_ap_done;
wire    grp_transmit_byte_fu_86_ap_idle;
wire    grp_transmit_byte_fu_86_ap_ready;
wire   [7:0] grp_transmit_byte_fu_86_out_SPI_D;
wire    grp_transmit_byte_fu_86_out_SPI_D_ap_vld;
wire   [0:0] grp_transmit_byte_fu_86_out_SPI_DS;
wire    grp_transmit_byte_fu_86_out_SPI_DS_ap_vld;
reg    grp_transmit_byte_fu_86_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [3:0] byte_i_fu_64;
wire   [3:0] byte_i_2_fu_125_p2;
wire   [0:0] icmp_ln9_fu_119_p2;
wire   [1:0] tmp_1_fu_135_p4;
wire   [6:0] and_ln_fu_145_p3;
wire   [95:0] zext_ln12_fu_153_p1;
wire   [95:0] lshr_ln12_fu_157_p2;
wire   [4:0] shl_ln_fu_171_p3;
wire   [31:0] zext_ln16_fu_178_p1;
wire   [31:0] lshr_ln16_fu_182_p2;
wire   [0:0] icmp_ln22_fu_202_p2;
wire   [7:0] or_ln25_fu_207_p2;
wire   [7:0] led_byte_i_2_fu_212_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_transmit_byte_fu_86_ap_start_reg = 1'b0;
#0 byte_i_fu_64 = 4'd0;
end

SK9822_transmit_byte grp_transmit_byte_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transmit_byte_fu_86_ap_start),
    .ap_done(grp_transmit_byte_fu_86_ap_done),
    .ap_idle(grp_transmit_byte_fu_86_ap_idle),
    .ap_ready(grp_transmit_byte_fu_86_ap_ready),
    .out_SPI_D(grp_transmit_byte_fu_86_out_SPI_D),
    .out_SPI_D_ap_vld(grp_transmit_byte_fu_86_out_SPI_D_ap_vld),
    .out_SPI_DS(grp_transmit_byte_fu_86_out_SPI_DS),
    .out_SPI_DS_ap_vld(grp_transmit_byte_fu_86_out_SPI_DS_ap_vld),
    .data(led_byte_i_3_reg_279)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transmit_byte_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_transmit_byte_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_transmit_byte_fu_86_ap_ready == 1'b1)) begin
            grp_transmit_byte_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        byte_i_fu_64 <= 4'd0;
    end else if (((icmp_ln9_fu_119_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        byte_i_fu_64 <= byte_i_2_fu_125_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LED_i_reg_258 <= LED_i_fu_162_p1;
        led_byte_id_reg_252 <= led_byte_id_fu_131_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        conv9_reg_244[4 : 0] <= conv9_fu_107_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln18_reg_268 <= icmp_ln18_fu_191_p2;
        led_byte_i_1_reg_273 <= led_byte_i_1_fu_196_p3;
        led_byte_i_reg_263 <= led_byte_i_fu_187_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        led_byte_i_3_reg_279 <= led_byte_i_3_fu_220_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_transmit_byte_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((icmp_ln9_fu_119_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_119_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln9_fu_119_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_transmit_byte_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LED_i_fu_162_p1 = lshr_ln12_fu_157_p2[31:0];

assign and_ln_fu_145_p3 = {{tmp_1_fu_135_p4}, {5'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign byte_i_2_fu_125_p2 = (byte_i_fu_64 + 4'd1);

assign conv9_fu_107_p1 = in_GBCR_GB_val;

assign grp_transmit_byte_fu_86_ap_start = grp_transmit_byte_fu_86_ap_start_reg;

assign icmp_ln18_fu_191_p2 = ((led_byte_id_reg_252 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_202_p2 = ((led_byte_i_1_reg_273 > 8'd8) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_119_p2 = ((byte_i_fu_64 == 4'd12) ? 1'b1 : 1'b0);

assign led_byte_i_1_fu_196_p3 = ((in_GBCR_INSEL_val[0:0] == 1'b1) ? led_byte_i_fu_187_p1 : conv9_reg_244);

assign led_byte_i_2_fu_212_p3 = ((icmp_ln22_fu_202_p2[0:0] == 1'b1) ? 8'd232 : or_ln25_fu_207_p2);

assign led_byte_i_3_fu_220_p3 = ((icmp_ln18_reg_268[0:0] == 1'b1) ? led_byte_i_2_fu_212_p3 : led_byte_i_reg_263);

assign led_byte_i_fu_187_p1 = lshr_ln16_fu_182_p2[7:0];

assign led_byte_id_fu_131_p1 = byte_i_fu_64[1:0];

assign lshr_ln12_fu_157_p2 = in_LEDs_val >> zext_ln12_fu_153_p1;

assign lshr_ln16_fu_182_p2 = LED_i_reg_258 >> zext_ln16_fu_178_p1;

assign or_ln25_fu_207_p2 = (led_byte_i_1_reg_273 | 8'd224);

assign out_SPI_D = grp_transmit_byte_fu_86_out_SPI_D;

assign out_SPI_DS = grp_transmit_byte_fu_86_out_SPI_DS;

assign out_SPI_DS_ap_vld = grp_transmit_byte_fu_86_out_SPI_DS_ap_vld;

assign out_SPI_D_ap_vld = grp_transmit_byte_fu_86_out_SPI_D_ap_vld;

assign shl_ln_fu_171_p3 = {{led_byte_id_reg_252}, {3'd0}};

assign tmp_1_fu_135_p4 = {{byte_i_fu_64[3:2]}};

assign zext_ln12_fu_153_p1 = and_ln_fu_145_p3;

assign zext_ln16_fu_178_p1 = shl_ln_fu_171_p3;

always @ (posedge ap_clk) begin
    conv9_reg_244[7:5] <= 3'b000;
end

endmodule //SK9822_transmit_fullcolors
