// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SK9822_transmit_end_bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_SPI_D,
        out_SPI_D_ap_vld,
        out_SPI_DS,
        out_SPI_DS_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] out_SPI_D;
output   out_SPI_D_ap_vld;
output  [0:0] out_SPI_DS;
output   out_SPI_DS_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_transmit_byte_fu_16_ap_start;
wire    grp_transmit_byte_fu_16_ap_done;
wire    grp_transmit_byte_fu_16_ap_idle;
wire    grp_transmit_byte_fu_16_ap_ready;
wire   [7:0] grp_transmit_byte_fu_16_out_SPI_D;
wire    grp_transmit_byte_fu_16_out_SPI_D_ap_vld;
wire   [0:0] grp_transmit_byte_fu_16_out_SPI_DS;
wire    grp_transmit_byte_fu_16_out_SPI_DS_ap_vld;
reg    grp_transmit_byte_fu_16_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_transmit_byte_fu_16_ap_start_reg = 1'b0;
end

SK9822_transmit_byte grp_transmit_byte_fu_16(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transmit_byte_fu_16_ap_start),
    .ap_done(grp_transmit_byte_fu_16_ap_done),
    .ap_idle(grp_transmit_byte_fu_16_ap_idle),
    .ap_ready(grp_transmit_byte_fu_16_ap_ready),
    .out_SPI_D(grp_transmit_byte_fu_16_out_SPI_D),
    .out_SPI_D_ap_vld(grp_transmit_byte_fu_16_out_SPI_D_ap_vld),
    .out_SPI_DS(grp_transmit_byte_fu_16_out_SPI_DS),
    .out_SPI_DS_ap_vld(grp_transmit_byte_fu_16_out_SPI_DS_ap_vld),
    .data(8'd0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transmit_byte_fu_16_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_transmit_byte_fu_16_ap_start_reg <= 1'b1;
        end else if ((grp_transmit_byte_fu_16_ap_ready == 1'b1)) begin
            grp_transmit_byte_fu_16_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_transmit_byte_fu_16_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_transmit_byte_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_transmit_byte_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_transmit_byte_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_transmit_byte_fu_16_ap_start = grp_transmit_byte_fu_16_ap_start_reg;

assign out_SPI_D = grp_transmit_byte_fu_16_out_SPI_D;

assign out_SPI_DS = grp_transmit_byte_fu_16_out_SPI_DS;

assign out_SPI_DS_ap_vld = grp_transmit_byte_fu_16_out_SPI_DS_ap_vld;

assign out_SPI_D_ap_vld = grp_transmit_byte_fu_16_out_SPI_D_ap_vld;

endmodule //SK9822_transmit_end_bytes
