set_property IOSTANDARD LVCMOS33 [get_ports SCLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports MOSI_0]
set_property IOSTANDARD LVCMOS33 [get_ports TI_0]
set_property PACKAGE_PIN C20 [get_ports SCLK_0]
set_property PACKAGE_PIN B20 [get_ports MOSI_0]
set_property PACKAGE_PIN F16 [get_ports TI_0]
